// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ActiveUsersReq struct {
	Symbol string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
}

type ActiveUsersResp struct {
	SignedUsers  int64  `json:"signedUsers,example=123"`
	Symbol       string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Participants int64  `json:"participants,example=1234"`
}

type ApyReq struct {
	Symbol string `json:"symbol,optional,example=cuniBTC"` //symbol of the strategy, empty indicate all
}

type ApyResp struct {
	Symbol string  `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Apy    float64 `json:"apy,example=0.05"`
}

type CurrentEpochReq struct {
	Symbol string `json:"symbol,optional,example=cuniBTC"` //symbol of the strategy, empty indicate all
}

type CurrentEpochResp struct {
	Epoch                 uint64 `json:"epoch,example=10"`                         //epoch number
	OperateStartTimestamp uint64 `json:"operateStartTimestamp,example=1777349793"` // operate startTime
	OperatePeriod         uint64 `json:"operatePeriod,example=86400"`              // operate period in second
	LockupStartTimestamp  uint64 `json:"lockupStartTimestamp,example=1777649793"`  //lockup startTime
	LockupPeriod          uint64 `json:"lockupPeriod,example=86400"`               //lockup period in second
	Symbol                string `json:"symbol,example=cuniBTC"`                   //symbol of the stratedy
}

type DistributeRewardsReq struct {
	Symbol       string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Epoch        uint64 `json:"epoch,example=10"`       //epoch number
	TotalRewards string `json:"totalRewards,example=0.123"`
}

type DistributeRewardsResp struct {
	DistributeRewardsReq
	Participants int64 `json:"participants,example=1234"`
}

type EpochInfo struct {
	CurrentEpochResp
	Participants int64   `json:"participants,example=1234"`
	Tvl          string  `json:"tvl,example=120.13"`
	Rewards      string  `json:"rewards,example=1112.34"`
	Claimed      string  `json:"claimed,example=123.45"`
	Apy          float64 `json:"apy,example=0.12345"`
	Root         string  `json:"root,example=0xbe61b01644a8590d584af06354d45f9347b68724aefc9d546cb15b5c78049741"`
	MerkleRoot   string  `json:"merkleRoot,example=0xbe61b01644a8590d584af06354d45f9347b68724aefc9d546cb15b5c78049741"`
	RewardToken  string  `json:"rewardToken,example=0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD"`
	SubmitAt     int64   `json:"submitAt,example=3234535"`
	SubmitBy     string  `json:"submitBy,example=abc@abc.com"`
}

type EpochInfoReq struct {
	Symbol string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Epoch  uint64 `json:"epoch,example=10"`       //epoch number
}

type EpochListReq struct {
	ListReq
	Symbol string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
}

type EpochListResp struct {
	PageData
	Data []EpochInfo `json:"data"`
}

type ListReq struct {
	Limit  int `json:"limit,example=10,default=10,range=[1:50]"` //Number of items per page
	Offset int `json:"offset,example=0,default=0"`               //Data offset
}

type PageData struct {
	Total  int64 `json:"total,example=1234"`         //Total data count
	Limit  int   `json:"limit,example=10"`           //Number of items per page, consistent with the request
	Offset int   `json:"offset,example=0,default=0"` //Data offset, consistent with the request
}

type PendingWithdrawalReq struct {
	Symbol string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
}

type PendingWithdrawalResp struct {
	Symbol    string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Requested string `json:"requested,example=12.34"`
	Requests  int64  `json:"requests,example=4"`
}

type PositionOverviewReq struct {
	Symbol  string `json:"symbol,optional,example=cuniBTC"` //symbol of the strategy, empty indicate all
	Address string `json:"address,example=0x8cb37518330014E027396E3ED59A231FBe3B011A"`
}

type PositionOverviewResp struct {
	Symbol      string `json:"symbol,example=cuniBTC"`       //symbol of the stratedy
	Amount      string `json:"amount,example=0.023"`         //amount of this symbol
	Earning     string `json:"earning,example=0.023243"`     //amount earning human readable
	Queued      string `json:"queued,example=0.023243"`      //amount queued human readable
	Withdrawing string `json:"withdrawing,example=0.023243"` //amount withdrawing human readable
	Rewards     string `json:"rewards,example=0.023243"`     //amount withdrawing human readable
}

type QueuedReq struct {
	Symbol string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
}

type QueuedResp struct {
	Amount   string `json:"amount,example=12.34"`
	Symbol   string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Deposits int64  `json:"deposits"`
}

type RewardProofs struct {
	Epoch   uint64   `json:"epoch,example=3"`
	Amount  string   `json:"amount,example=12.34"`
	Claimed bool     `json:"claimed,example=true|false"`
	Proofs  []string `json:"proofs"`
}

type RewardProofsReq struct {
	Symbol  string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Address string `json:"address,example=0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD"`
}

type RewardProofsResp struct {
	TotalAmount  string         `json:"totalAmount,example=1.23"`
	RewardProofs []RewardProofs `json:"rewardProofs"`
}

type SignTermsReq struct {
	Message   string `json:"message,example=SIWE exposes a Message struct which implements EIP-4361" validate:"max=81920"`
	Signature string `json:"signature,example=0x4c46904b62a8889db17b3d84b129eea1283e6313f6ca635802e95d4da72bf06f74b270b1fd28de9f0931cf0ca079229d5088743ae117e743a17af2205b0dda6a1c" validate:"max=256"`
	Symbol    string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
}

type SignTermsResp struct {
	Address  string `json:"address,example=0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD"`
	TermsMd5 string `json:"termsMd5,example=5eb63bbbe01eeed093cb22bb8f5acdc3"`
	Symbol   string `json:"symbol"`
}

type SignTermsStatusReq struct {
	Address string `json:"address,example=0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD"`
	Symbol  string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
}

type SignTermsStatusResp struct {
	Signed      bool   `json:"signed,example=false|true"`
	TermsMd5    string `json:"termsMd5,example=5eb63bbbe01eeed093cb22bb8f5acdc3"`
	Symbol      string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Address     string `json:"address,example=0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD"`
	MessageHash string `json:"messageHash,example=0x0343453"`
}

type TotalEarnedReq struct {
	Symbol  string `json:"symbol,optional,example=cuniBTC"` //symbol of the strategy, empty indicate all
	Address string `json:"address,example=0x8cb37518330014E027396E3ED59A231FBe3B011A"`
}

type TotalEarnedResp struct {
	Symbol      string `json:"symbol,example=cuniBTC"`       //symbol of the stratedy
	TotalEarned string `json:"totalEarned,example=0.023243"` //amount earned human readable
}

type UserAction struct {
	CurrentEpochResp
	Address   string `json:"address,example=0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD"`
	Deposited string `json:"deposited,example=120.13"`
	Rewards   string `json:"rewards,example=0.34"`
	Queued    string `json:"queued,example=2.34"`
	ClaimAt   uint64 `json:"claimAt,example=1777349793"`
	Claimed   bool   `json:"claimed,example=true|false"`
}

type UserActionListResp struct {
	PageData
	Data []UserAction `json:"data"`
}

type UserActionsListReq struct {
	ListReq
	Symbol string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Epoch  uint64 `json:"epoch,example=10"`       //epoch number
}

type WithdrawalHistoryReq struct {
	Symbol string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
}

type WithdrawalHistoryResp struct {
	Symbol    string `json:"symbol,example=cuniBTC"` //symbol of the stratedy
	Requested string `json:"requested,example=12.34"`
	Requests  int64  `json:"requests,example=4"`
	Claimed   string `json:"claimed,example=21.2"`
}

type WithdrawalInfo struct {
	Address  string `json:"address,example=0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD"`
	Amount   string `json:"amount,example=0.23"`
	Epoch    uint64 `json:"epoch,example=3"`
	CreateAt int64  `json:"createAt,example=1784105760"`
	ClaimAt  int64  `json:"claimAt,example=1777349793"`
	Claimed  bool   `json:"claimed,example=true|false"`
}

type WithdrawalListReq struct {
	ListReq
	Symbol  string `json:"symbol,example=cuniBTC"`
	Epoch   string `json:"epoch,optional,example=10"`
	Status  string `json:"status,optional,example=claimed|unClaimed|coolingDown"`
	Address string `json:"address,optional,example=0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD"`
	Start   int64  `json:"start,optional,example=1784105760"`
	End     int64  `json:"end,optional,example=1784105760"`
}

type WithdrawalListResp struct {
	PageData
	Data []WithdrawalInfo `json:"data"`
}

type WithdrawalRequestsInfo struct {
	Amount   string `json:"amount,example=0.23"`
	CreateAt int64  `json:"createAt,example=1784105760"`
	Claimed  bool   `json:"claimed,example=true|false"`
}

type WithdrawalRequestsListReq struct {
	ListReq
	Symbol  string `json:"symbol,example=cuniBTC"`
	Address string `json:"address,example=0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD"`
}

type WithdrawalRequestsListResp struct {
	PageData
	Data []WithdrawalRequestsInfo `json:"data"`
}
