// Command openapi3 converts the Swagger 2.0 document generated by goctl to
// OpenAPI 3.0.3. It is intentionally dependency-free so documentation can be
// regenerated with only Go and goctl installed.
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	input := flag.String("in", "", "path to the Swagger 2.0 JSON document")
	output := flag.String("out", "", "path for the OpenAPI 3.0 JSON document (defaults to -in)")
	typesFile := flag.String("types", "", "optional Go types file used to restore numeric formats")
	flag.Parse()

	if *input == "" {
		flag.Usage()
		os.Exit(2)
	}
	if *output == "" {
		*output = *input
	}

	if err := convertFile(*input, *output, *typesFile); err != nil {
		fmt.Fprintln(os.Stderr, "openapi3:", err)
		os.Exit(1)
	}
}

func convertFile(input, output, typesFile string) error {
	data, err := os.ReadFile(input)
	if err != nil {
		return err
	}
	mode := os.FileMode(0o644)
	if info, statErr := os.Stat(output); statErr == nil {
		mode = info.Mode().Perm()
	}

	var document map[string]any
	if err := json.Unmarshal(data, &document); err != nil {
		return fmt.Errorf("decode %s: %w", input, err)
	}
	if err := convert(document); err != nil {
		return err
	}
	if typesFile != "" {
		formats, err := formatsFromGoFile(typesFile)
		if err != nil {
			return err
		}
		applyFormats(document, formats)
	}

	data, err = json.MarshalIndent(document, "", "  ")
	if err != nil {
		return fmt.Errorf("encode OpenAPI document: %w", err)
	}
	data = append(data, '\n')

	dir := filepath.Dir(output)
	temporary, err := os.CreateTemp(dir, ".openapi3-*.json")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)

	if _, err := temporary.Write(data); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryName, output); err != nil {
		return err
	}
	return nil
}

func convert(document map[string]any) error {
	if version, _ := document["openapi"].(string); strings.HasPrefix(version, "3.") {
		return nil
	}
	if document["swagger"] != "2.0" {
		return errors.New("input must be a Swagger 2.0 or OpenAPI 3.x document")
	}

	consumes := stringList(document["consumes"], "application/json")
	produces := stringList(document["produces"], "application/json")

	paths, ok := document["paths"].(map[string]any)
	if !ok {
		return errors.New("input has no paths object")
	}
	for _, pathValue := range paths {
		pathItem, ok := pathValue.(map[string]any)
		if !ok {
			continue
		}
		if parameters, ok := pathItem["parameters"].([]any); ok {
			if err := convertParameters(parameters); err != nil {
				return fmt.Errorf("convert path parameters: %w", err)
			}
		}
		for method, operationValue := range pathItem {
			if method == "parameters" || strings.HasPrefix(method, "x-") {
				continue
			}
			operation, ok := operationValue.(map[string]any)
			if !ok {
				continue
			}
			operationConsumes := stringList(operation["consumes"], consumes...)
			operationProduces := stringList(operation["produces"], produces...)
			if err := convertOperation(operation, operationConsumes, operationProduces); err != nil {
				return fmt.Errorf("convert %s operation: %w", method, err)
			}
			delete(operation, "consumes")
			delete(operation, "produces")
			delete(operation, "schemes")
		}
	}

	components := map[string]any{}
	if schemas, ok := document["definitions"]; ok {
		components["schemas"] = schemas
	}
	if securitySchemes, ok := document["securityDefinitions"]; ok {
		components["securitySchemes"] = securitySchemes
	}
	if parameters, ok := document["parameters"]; ok {
		components["parameters"] = parameters
	}
	if responses, ok := document["responses"]; ok {
		components["responses"] = responses
	}
	if parameters, ok := components["parameters"].(map[string]any); ok {
		for name, parameterValue := range parameters {
			parameter, ok := parameterValue.(map[string]any)
			if !ok {
				continue
			}
			if parameter["in"] == "body" || parameter["in"] == "formData" {
				return fmt.Errorf("shared parameter %q uses unsupported location %q", name, parameter["in"])
			}
			if err := convertParameter(parameter); err != nil {
				return fmt.Errorf("convert shared parameter %q: %w", name, err)
			}
		}
	}

	normalizeArrayRefs(document)
	rewriteRefs(document)
	document["openapi"] = "3.0.3"
	delete(document, "x-date")
	if _, ok := document["x-description"]; ok {
		document["x-description"] = "Converted from a goctl-generated Swagger document."
	}
	if len(components) > 0 {
		document["components"] = components
	}
	if servers := servers(document); len(servers) > 0 {
		document["servers"] = servers
	}

	for _, key := range []string{
		"swagger", "host", "basePath", "schemes", "consumes", "produces",
		"definitions", "securityDefinitions", "parameters", "responses",
	} {
		delete(document, key)
	}
	return nil
}

func convertOperation(operation map[string]any, consumes, produces []string) error {
	if parameters, ok := operation["parameters"].([]any); ok {
		remaining := make([]any, 0, len(parameters))
		for _, parameterValue := range parameters {
			parameter, ok := parameterValue.(map[string]any)
			if !ok {
				remaining = append(remaining, parameterValue)
				continue
			}
			if parameter["in"] == "formData" {
				return errors.New("formData parameters are not supported")
			}
			if parameter["in"] != "body" {
				if err := convertParameter(parameter); err != nil {
					return err
				}
				remaining = append(remaining, parameterValue)
				continue
			}
			if _, exists := operation["requestBody"]; exists {
				return errors.New("multiple body parameters are not supported")
			}
			requestBody := map[string]any{
				"content": content(consumes, parameter["schema"]),
			}
			if value, ok := parameter["description"]; ok {
				requestBody["description"] = value
			}
			if value, ok := parameter["required"]; ok {
				requestBody["required"] = value
			}
			operation["requestBody"] = requestBody
		}
		if len(remaining) == 0 {
			delete(operation, "parameters")
		} else {
			operation["parameters"] = remaining
		}
	}

	responses, _ := operation["responses"].(map[string]any)
	for _, responseValue := range responses {
		response, ok := responseValue.(map[string]any)
		if !ok {
			continue
		}
		if description, _ := response["description"].(string); description == "" {
			response["description"] = "Successful response"
		}
		if schema, ok := response["schema"]; ok {
			response["content"] = content(produces, schema)
			delete(response, "schema")
		}
	}
	return nil
}

func convertParameters(parameters []any) error {
	for _, parameterValue := range parameters {
		parameter, ok := parameterValue.(map[string]any)
		if !ok || parameter["$ref"] != nil {
			continue
		}
		if parameter["in"] == "body" || parameter["in"] == "formData" {
			return fmt.Errorf("parameter %q uses unsupported location %q", parameter["name"], parameter["in"])
		}
		if err := convertParameter(parameter); err != nil {
			return err
		}
	}
	return nil
}

func convertParameter(parameter map[string]any) error {
	if _, ok := parameter["schema"]; ok {
		return nil
	}
	if parameter["type"] == "file" {
		return fmt.Errorf("file parameter %q is not supported", parameter["name"])
	}

	schemaKeys := []string{
		"type", "format", "items", "default", "maximum", "minimum",
		"exclusiveMaximum", "exclusiveMinimum", "maxLength", "minLength",
		"pattern", "maxItems", "minItems", "uniqueItems", "enum", "multipleOf",
	}
	schema := map[string]any{}
	for _, key := range schemaKeys {
		if value, ok := parameter[key]; ok {
			schema[key] = value
			delete(parameter, key)
		}
	}
	if len(schema) == 0 {
		return fmt.Errorf("parameter %q has no schema", parameter["name"])
	}
	parameter["schema"] = schema

	if collectionFormat, ok := parameter["collectionFormat"].(string); ok {
		if err := applyCollectionFormat(parameter, collectionFormat); err != nil {
			return err
		}
		delete(parameter, "collectionFormat")
	}
	return nil
}

func applyCollectionFormat(parameter map[string]any, collectionFormat string) error {
	location, _ := parameter["in"].(string)
	switch collectionFormat {
	case "multi":
		parameter["style"] = "form"
		parameter["explode"] = true
	case "csv", "":
		if location == "query" || location == "cookie" {
			parameter["style"] = "form"
		} else {
			parameter["style"] = "simple"
		}
		parameter["explode"] = false
	case "ssv":
		parameter["style"] = "spaceDelimited"
		parameter["explode"] = false
	case "pipes":
		parameter["style"] = "pipeDelimited"
		parameter["explode"] = false
	default:
		return fmt.Errorf("parameter %q uses unsupported collectionFormat %q", parameter["name"], collectionFormat)
	}
	return nil
}

func content(mediaTypes []string, schema any) map[string]any {
	result := make(map[string]any, len(mediaTypes))
	for _, mediaType := range mediaTypes {
		result[mediaType] = map[string]any{"schema": schema}
	}
	return result
}

func servers(document map[string]any) []any {
	host, _ := document["host"].(string)
	basePath, _ := document["basePath"].(string)
	if basePath == "" {
		basePath = "/"
	}
	if host == "" {
		return []any{map[string]any{"url": basePath}}
	}

	schemes := stringList(document["schemes"], "https")
	result := make([]any, 0, len(schemes))
	for _, scheme := range schemes {
		result = append(result, map[string]any{"url": scheme + "://" + host + basePath})
	}
	return result
}

func rewriteRefs(value any) {
	switch value := value.(type) {
	case map[string]any:
		for key, child := range value {
			if key == "$ref" {
				if ref, ok := child.(string); ok {
					ref = strings.Replace(ref, "#/definitions/", "#/components/schemas/", 1)
					ref = strings.Replace(ref, "#/securityDefinitions/", "#/components/securitySchemes/", 1)
					ref = strings.Replace(ref, "#/parameters/", "#/components/parameters/", 1)
					ref = strings.Replace(ref, "#/responses/", "#/components/responses/", 1)
					value[key] = ref
				}
				continue
			}
			rewriteRefs(child)
		}
	case []any:
		for _, child := range value {
			rewriteRefs(child)
		}
	}
}

func normalizeArrayRefs(value any) {
	switch value := value.(type) {
	case map[string]any:
		ref, hasRef := value["$ref"].(string)
		_, hasItems := value["items"]
		_, hasType := value["type"]
		if hasRef && hasItems && !hasType {
			delete(value, "$ref")
			value["type"] = "array"
			value["items"] = map[string]any{"$ref": ref}
		}
		for _, child := range value {
			normalizeArrayRefs(child)
		}
	case []any:
		for _, child := range value {
			normalizeArrayRefs(child)
		}
	}
}

func stringList(value any, defaults ...string) []string {
	values, ok := value.([]any)
	if !ok || len(values) == 0 {
		return defaults
	}
	result := make([]string, 0, len(values))
	for _, value := range values {
		if text, ok := value.(string); ok {
			result = append(result, text)
		}
	}
	if len(result) == 0 {
		return defaults
	}
	return result
}
