// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

// ActiveUsersReq defines model for ActiveUsersReq.
type ActiveUsersReq struct {
	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// ActiveUsersResp defines model for ActiveUsersResp.
type ActiveUsersResp struct {
	// Participants Example: 1234
	Participants int64 `json:"participants"`

	// SignedUsers Example: 123
	SignedUsers int64 `json:"signedUsers"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// ApyReq defines model for ApyReq.
type ApyReq struct {
	// Symbol symbol of the strategy, empty indicate all
	//
	// Example: cuniBTC
	Symbol *string `json:"symbol,omitempty"`
}

// ApyResp defines model for ApyResp.
type ApyResp struct {
	// Apy Example: 0.05
	Apy float64 `json:"apy"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// CurrentEpochReq defines model for CurrentEpochReq.
type CurrentEpochReq struct {
	// Symbol symbol of the strategy, empty indicate all
	//
	// Example: cuniBTC
	Symbol *string `json:"symbol,omitempty"`
}

// DistributeRewardsReq defines model for DistributeRewardsReq.
type DistributeRewardsReq struct {
	// Epoch epoch number
	//
	// Example: 10
	Epoch uint64 `json:"epoch"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`

	// TotalRewards Example: 0.123
	TotalRewards string `json:"totalRewards"`
}

// DistributeRewardsResp defines model for DistributeRewardsResp.
type DistributeRewardsResp struct {
	// Epoch epoch number
	//
	// Example: 10
	Epoch uint64 `json:"epoch"`

	// Participants Example: 1234
	Participants int64 `json:"participants"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`

	// TotalRewards Example: 0.123
	TotalRewards string `json:"totalRewards"`
}

// EpochInfo defines model for EpochInfo.
type EpochInfo struct {
	// Apy Example: 0.12345
	Apy float64 `json:"apy"`

	// Claimed Example: 123.45
	Claimed string `json:"claimed"`

	// Creator Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Creator string `json:"creator"`

	// CreatorAt Example: 3234535
	CreatorAt int64 `json:"creatorAt"`

	// Epoch epoch number
	//
	// Example: 10
	Epoch uint64 `json:"epoch"`

	// LockupPeriod lockup period in second
	//
	// Example: 86400
	LockupPeriod uint64 `json:"lockupPeriod"`

	// LockupStartTimestamp lockup startTime
	//
	// Example: 1777649793
	LockupStartTimestamp uint64 `json:"lockupStartTimestamp"`

	// MerkleRoot Example: 0xbe61b01644a8590d584af06354d45f9347b68724aefc9d546cb15b5c78049741
	MerkleRoot string `json:"merkleRoot"`

	// OperatePeriod operate period in second
	//
	// Example: 86400
	OperatePeriod uint64 `json:"operatePeriod"`

	// OperateStartTimestamp operate startTime
	//
	// Example: 1777349793
	OperateStartTimestamp uint64 `json:"operateStartTimestamp"`

	// Participants Example: 1234
	Participants int64 `json:"participants"`

	// Queued Example: 13.45
	Queued string `json:"queued"`

	// RewardToken Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	RewardToken string `json:"rewardToken"`

	// Rewards Example: 1112.34
	Rewards string `json:"rewards"`

	// Root Example: 0xbe61b01644a8590d584af06354d45f9347b68724aefc9d546cb15b5c78049741
	Root string `json:"root"`

	// SubmitAt Example: 3234535
	SubmitAt int64 `json:"submitAt"`

	// SubmitBy Example: abc@abc.com
	SubmitBy string `json:"submitBy"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`

	// Tvl Example: 120.13
	Tvl string `json:"tvl"`
}

// EpochInfoReq defines model for EpochInfoReq.
type EpochInfoReq struct {
	// Epoch epoch number
	//
	// Example: 10
	Epoch uint64 `json:"epoch"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// EpochListReq defines model for EpochListReq.
type EpochListReq struct {
	// Limit Number of items per page
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset
	//
	// Example: 0
	Offset int `json:"offset"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// EpochListResp defines model for EpochListResp.
type EpochListResp struct {
	Data []EpochInfo `json:"data"`

	// Limit Number of items per page, consistent with the request
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset, consistent with the request
	//
	// Example: 0
	Offset int `json:"offset"`

	// Total Total data count
	//
	// Example: 1234
	Total int64 `json:"total"`
}

// PendingWithdrawalReq defines model for PendingWithdrawalReq.
type PendingWithdrawalReq struct {
	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// PendingWithdrawalResp defines model for PendingWithdrawalResp.
type PendingWithdrawalResp struct {
	// Requested Example: 12.34
	Requested string `json:"requested"`

	// Requests Example: 4
	Requests int64 `json:"requests"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// PositionOverviewReq defines model for PositionOverviewReq.
type PositionOverviewReq struct {
	// Address Example: 0x8cb37518330014E027396E3ED59A231FBe3B011A
	Address string `json:"address"`

	// Symbol symbol of the strategy, empty indicate all
	//
	// Example: cuniBTC
	Symbol *string `json:"symbol,omitempty"`
}

// PositionOverviewResp defines model for PositionOverviewResp.
type PositionOverviewResp struct {
	// Amount amount of this symbol
	//
	// Example: 0.023
	Amount string `json:"amount"`

	// Earning amount earning human readable
	//
	// Example: 0.023243
	Earning string `json:"earning"`

	// Queued amount queued human readable
	//
	// Example: 0.023243
	Queued string `json:"queued"`

	// Rewards amount withdrawing human readable
	//
	// Example: 0.023243
	Rewards string `json:"rewards"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`

	// TotalRewards amount withdrawing human readable
	//
	// Example: 0.023243
	TotalRewards string `json:"totalRewards"`

	// Withdrawing amount withdrawing human readable
	//
	// Example: 0.023243
	Withdrawing string `json:"withdrawing"`
}

// QueuedInfo defines model for QueuedInfo.
type QueuedInfo struct {
	// Address Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Address string `json:"address"`

	// CreateAt Example: 34354465
	CreateAt int64 `json:"createAt"`

	// Queued Example: 2.34
	Queued string `json:"queued"`
}

// QueuedListReq defines model for QueuedListReq.
type QueuedListReq struct {
	// Limit Number of items per page
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset
	//
	// Example: 0
	Offset int `json:"offset"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// QueuedListResp defines model for QueuedListResp.
type QueuedListResp struct {
	Data []QueuedInfo `json:"data"`

	// Limit Number of items per page, consistent with the request
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset, consistent with the request
	//
	// Example: 0
	Offset int `json:"offset"`

	// Total Total data count
	//
	// Example: 1234
	Total int64 `json:"total"`
}

// QueuedReq defines model for QueuedReq.
type QueuedReq struct {
	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// QueuedResp defines model for QueuedResp.
type QueuedResp struct {
	// Amount Example: 12.34
	Amount   string `json:"amount"`
	Deposits int64  `json:"deposits"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// RewardProofs defines model for RewardProofs.
type RewardProofs struct {
	// Amount Example: 12.34
	Amount string `json:"amount"`

	// Claimed Example: false
	Claimed bool `json:"claimed"`

	// Epoch Example: 3
	Epoch  uint64   `json:"epoch"`
	Proofs []string `json:"proofs"`
}

// RewardProofsReq defines model for RewardProofsReq.
type RewardProofsReq struct {
	// Address Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Address string `json:"address"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// RewardProofsResp defines model for RewardProofsResp.
type RewardProofsResp struct {
	RewardProofs []RewardProofs `json:"rewardProofs"`

	// TotalAmount Example: 1.23
	TotalAmount string `json:"totalAmount"`
}

// RewardSummaryReq defines model for RewardSummaryReq.
type RewardSummaryReq struct {
	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// RewardSummaryResp defines model for RewardSummaryResp.
type RewardSummaryResp struct {
	// Claimed Example: 23.8
	Claimed string `json:"claimed"`

	// Total Example: 12.34
	Total string `json:"total"`

	// UnClaimed Example: 23.8
	UnClaimed string `json:"unClaimed"`
}

// SignTermsReq defines model for SignTermsReq.
type SignTermsReq struct {
	// Message Example: SIWE exposes a Message struct which implements EIP-4361
	Message string `json:"message"`

	// Signature Example: 0x4c46904b62a8889db17b3d84b129eea1283e6313f6ca635802e95d4da72bf06f74b270b1fd28de9f0931cf0ca079229d5088743ae117e743a17af2205b0dda6a1c
	Signature string `json:"signature"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// SignTermsResp defines model for SignTermsResp.
type SignTermsResp struct {
	// Address Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Address string `json:"address"`
	Symbol  string `json:"symbol"`

	// TermsMd5 Example: 5eb63bbbe01eeed093cb22bb8f5acdc3
	TermsMd5 string `json:"termsMd5"`
}

// SignTermsStatusReq defines model for SignTermsStatusReq.
type SignTermsStatusReq struct {
	// Address Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Address string `json:"address"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// SignTermsStatusResp defines model for SignTermsStatusResp.
type SignTermsStatusResp struct {
	// Address Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Address string `json:"address"`

	// MessageHash Example: 0x0343453
	MessageHash string `json:"messageHash"`

	// Signed Example: false
	Signed bool `json:"signed"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`

	// TermsMd5 Example: 5eb63bbbe01eeed093cb22bb8f5acdc3
	TermsMd5 string `json:"termsMd5"`
}

// TotalEarnedReq defines model for TotalEarnedReq.
type TotalEarnedReq struct {
	// Address Example: 0x8cb37518330014E027396E3ED59A231FBe3B011A
	Address string `json:"address"`

	// Symbol symbol of the strategy, empty indicate all
	//
	// Example: cuniBTC
	Symbol *string `json:"symbol,omitempty"`
}

// TotalEarnedResp defines model for TotalEarnedResp.
type TotalEarnedResp struct {
	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`

	// TotalEarned amount earned human readable
	//
	// Example: 0.023243
	TotalEarned string `json:"totalEarned"`
}

// UserAction defines model for UserAction.
type UserAction struct {
	// Address Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Address string `json:"address"`

	// ClaimAt Example: 1777349793
	ClaimAt uint64 `json:"claimAt"`

	// Claimed Example: false
	Claimed bool `json:"claimed"`

	// Deposited Example: 120.13
	Deposited string `json:"deposited"`

	// Epoch epoch number
	//
	// Example: 10
	Epoch uint64 `json:"epoch"`

	// LockupPeriod lockup period in second
	//
	// Example: 86400
	LockupPeriod uint64 `json:"lockupPeriod"`

	// LockupStartTimestamp lockup startTime
	//
	// Example: 1777649793
	LockupStartTimestamp uint64 `json:"lockupStartTimestamp"`

	// OperatePeriod operate period in second
	//
	// Example: 86400
	OperatePeriod uint64 `json:"operatePeriod"`

	// OperateStartTimestamp operate startTime
	//
	// Example: 1777349793
	OperateStartTimestamp uint64 `json:"operateStartTimestamp"`

	// Queued Example: 2.34
	Queued string `json:"queued"`

	// Rewards Example: 0.34
	Rewards string `json:"rewards"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// UserActionListResp defines model for UserActionListResp.
type UserActionListResp struct {
	Data []UserAction `json:"data"`

	// Limit Number of items per page, consistent with the request
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset, consistent with the request
	//
	// Example: 0
	Offset int `json:"offset"`

	// Total Total data count
	//
	// Example: 1234
	Total int64 `json:"total"`
}

// UserActionsListReq defines model for UserActionsListReq.
type UserActionsListReq struct {
	// Epoch epoch number
	//
	// Example: 10
	Epoch uint64 `json:"epoch"`

	// Limit Number of items per page
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset
	//
	// Example: 0
	Offset int `json:"offset"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// WithdrawalHistoryReq defines model for WithdrawalHistoryReq.
type WithdrawalHistoryReq struct {
	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// WithdrawalHistoryResp defines model for WithdrawalHistoryResp.
type WithdrawalHistoryResp struct {
	// Claimed Example: 21.2
	Claimed string `json:"claimed"`

	// Requested Example: 12.34
	Requested string `json:"requested"`

	// Requests Example: 4
	Requests int64 `json:"requests"`

	// Symbol symbol of the stratedy
	//
	// Example: cuniBTC
	Symbol string `json:"symbol"`
}

// WithdrawalInfo defines model for WithdrawalInfo.
type WithdrawalInfo struct {
	// Address Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Address string `json:"address"`

	// Amount Example: 0.23
	Amount string `json:"amount"`

	// ClaimAt Example: 1777349793
	ClaimAt int64 `json:"claimAt"`

	// Claimed Example: false
	Claimed bool `json:"claimed"`

	// CreateAt Example: 1784105760
	CreateAt int64 `json:"createAt"`

	// Epoch Example: 3
	Epoch uint64 `json:"epoch"`
}

// WithdrawalListReq defines model for WithdrawalListReq.
type WithdrawalListReq struct {
	// Address Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Address *string `json:"address,omitempty"`

	// End Example: 1784105760
	End *int64 `json:"end,omitempty"`

	// Epoch Example: 10
	Epoch *string `json:"epoch,omitempty"`

	// Limit Number of items per page
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset
	//
	// Example: 0
	Offset int `json:"offset"`

	// Start Example: 1784105760
	Start *int64 `json:"start,omitempty"`

	// Status Example: claimed|unClaimed|coolingDown
	Status *string `json:"status,omitempty"`

	// Symbol Example: cuniBTC
	Symbol string `json:"symbol"`
}

// WithdrawalListResp defines model for WithdrawalListResp.
type WithdrawalListResp struct {
	Data []WithdrawalInfo `json:"data"`

	// Limit Number of items per page, consistent with the request
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset, consistent with the request
	//
	// Example: 0
	Offset int `json:"offset"`

	// Total Total data count
	//
	// Example: 1234
	Total int64 `json:"total"`
}

// WithdrawalRequestsInfo defines model for WithdrawalRequestsInfo.
type WithdrawalRequestsInfo struct {
	// Amount Example: 0.23
	Amount string `json:"amount"`

	// Claimed Example: false
	Claimed bool `json:"claimed"`

	// CreateAt Example: 1784105760
	CreateAt int64 `json:"createAt"`
}

// WithdrawalRequestsListReq defines model for WithdrawalRequestsListReq.
type WithdrawalRequestsListReq struct {
	// Address Example: 0xbf63Fba8137ce3043289f1BDbdC1700f65ee1aAD
	Address string `json:"address"`

	// Limit Number of items per page
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset
	//
	// Example: 0
	Offset int `json:"offset"`

	// Symbol Example: cuniBTC
	Symbol string `json:"symbol"`
}

// WithdrawalRequestsListResp defines model for WithdrawalRequestsListResp.
type WithdrawalRequestsListResp struct {
	Data []WithdrawalRequestsInfo `json:"data"`

	// Limit Number of items per page, consistent with the request
	//
	// Example: 10
	Limit int `json:"limit"`

	// Offset Data offset, consistent with the request
	//
	// Example: 0
	Offset int `json:"offset"`

	// Total Total data count
	//
	// Example: 1234
	Total int64 `json:"total"`
}

// ApyJSONRequestBody defines body for Apy for application/json ContentType.
type ApyJSONRequestBody = ApyReq

// ActiveUsersJSONRequestBody defines body for ActiveUsers for application/json ContentType.
type ActiveUsersJSONRequestBody = ActiveUsersReq

// DistributeRewardsJSONRequestBody defines body for DistributeRewards for application/json ContentType.
type DistributeRewardsJSONRequestBody = DistributeRewardsReq

// EpochInfoJSONRequestBody defines body for EpochInfo for application/json ContentType.
type EpochInfoJSONRequestBody = EpochInfoReq

// EpochListJSONRequestBody defines body for EpochList for application/json ContentType.
type EpochListJSONRequestBody = EpochListReq

// PendingWithdrawalJSONRequestBody defines body for PendingWithdrawal for application/json ContentType.
type PendingWithdrawalJSONRequestBody = PendingWithdrawalReq

// QueueJSONRequestBody defines body for Queue for application/json ContentType.
type QueueJSONRequestBody = QueuedReq

// QueuedListJSONRequestBody defines body for QueuedList for application/json ContentType.
type QueuedListJSONRequestBody = QueuedListReq

// RewardSummaryJSONRequestBody defines body for RewardSummary for application/json ContentType.
type RewardSummaryJSONRequestBody = RewardSummaryReq

// UserActionsJSONRequestBody defines body for UserActions for application/json ContentType.
type UserActionsJSONRequestBody = UserActionsListReq

// WithdrawalHistoryJSONRequestBody defines body for WithdrawalHistory for application/json ContentType.
type WithdrawalHistoryJSONRequestBody = WithdrawalHistoryReq

// WithdrawalListJSONRequestBody defines body for WithdrawalList for application/json ContentType.
type WithdrawalListJSONRequestBody = WithdrawalListReq

// CurrentEpochJSONRequestBody defines body for CurrentEpoch for application/json ContentType.
type CurrentEpochJSONRequestBody = CurrentEpochReq

// PositionOverviewJSONRequestBody defines body for PositionOverview for application/json ContentType.
type PositionOverviewJSONRequestBody = PositionOverviewReq

// RewardProofsJSONRequestBody defines body for RewardProofs for application/json ContentType.
type RewardProofsJSONRequestBody = RewardProofsReq

// SignTermsJSONRequestBody defines body for SignTerms for application/json ContentType.
type SignTermsJSONRequestBody = SignTermsReq

// SignTermsStatusJSONRequestBody defines body for SignTermsStatus for application/json ContentType.
type SignTermsStatusJSONRequestBody = SignTermsStatusReq

// TotalEarnedJSONRequestBody defines body for TotalEarned for application/json ContentType.
type TotalEarnedJSONRequestBody = TotalEarnedReq

// WithdrawalRequestsListReqJSONRequestBody defines body for WithdrawalRequestsListReq for application/json ContentType.
type WithdrawalRequestsListReqJSONRequestBody = WithdrawalRequestsListReq
